#ifndef FREEBASIC_COMPILER_COMPILATIONERRORS_H
#define FREEBASIC_COMPILER_COMPILATIONERRORS_H

enum ExitErrorCodes {
	ER_EXIT_LEXICAL_ANALYSIS = 1,
	ER_EXIT_SYNTAX_ANALYSIS = 2,
	ER_EXIT_SEMANTIC_DEFINITIONS = 3,
	ER_EXIT_SEMANTIC_TYPES = 4,
	ER_EXIT_SEMANTIC_OTHER = 6,
	ER_EXIT_INTERNAL = 99
};

#endif //FREEBASIC_COMPILER_COMPILATIONERRORS_H
