#ifndef FREEBASIC_COMPILER_LLTABLE_H
#define FREEBASIC_COMPILER_LLTABLE_H

#include <stdbool.h>
#include "Symbol.h"
#include "Token.h"

typedef enum Rules {
	RULE_MISSING,
	RULE_EPSILON,
	RULE_MAIN_SCOPE,
	RULE_FUNC_DECL,
	RULE_FUNC_DEF,
	RULE_FUNC_HEADER,
	RULE_FUNC_BODY,
	RULE_FUNC_ARG,
	RULE_FUNC_NEXT_ARG,
	RULE_ST_LIST,
	RULE_ST_VAR_DECL,
	RULE_ST_FUNC_CALL,
	RULE_ST_INPUT,
	RULE_ST_PRINT,
	RULE_ST_WHILE,
	RULE_ST_RETURN,
	RULE_ST_IF,
	RULE_ELSEIF,
	RULE_ELSE,
	RULE_END_IF,
	RULE_NEXT_EXPR,
	RULE_VAR_INIT,
	RULE_TYPE_STRING,
	RULE_TYPE_INT,
	RULE_TYPE_DOUBLE,
	RULE_LINE_BREAK,
	RULE_VAR_GLOBAL,
	RULE_ST_VAR_STATIC,
	RULE_NEW_SCOPE
} Rules;

typedef unsigned char Rule;

Rule GetLLRule(NTerminal nTerminal, Terminal tokenTerminal);

//const char* GetTerminalValue(Terminal terminal);


#endif //FREEBASIC_COMPILER_LLTABLE_H
